"""
Command to sign the Minecraft EULA
"""
import sys
import click
from rich.console import Console

console = Console()

@click.command("sign")
def sign_eula():
    """Sign the EULA by creating eula.txt."""
    try:
        with open("eula.txt", "w") as f:
            f.write("# Generated by Nex\n")
            f.write("eula=true\n")
        console.print("[green]EULA signed successfully.[/green]")
    except Exception as e:
        console.print(f"[red]Error: {str(e)}[/red]")
        sys.exit(1) 